[tool.poetry]
name = "sotopia-rl"
version = "0.0.1"
description = "Online RL framework for sotopia social agents."
authors = ["Haofei Yu <yuhaofei44@gmail.com>"]
license = "MIT License"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.9, <3.12"
mypy = "^1.8.0"
pydantic = "^1.9.0"
datasets = "^1.12.0"
openai = "^1.20.0"
types-tqdm = "^4.61.0"
rich = "^13.7.0"
pandas-stubs = "^2.2.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "*"
nbmake = "*"
types-setuptools = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-asyncio = "*"

[tool.poetry.extras]
deepspeed = ["deepspeed>=0.10.0"]
bitsandbytes = ["bitsandbytes>=0.39.0"]
vllm = ["vllm>=0.4.0"]
galore = ["galore-torch"]
badam = ["badam"]
gptq = ["optimum>=1.16.0", "auto-gptq>=0.5.0"]
awq = ["autoawq"]
aqlm = ["aqlm[gpu]>=1.1.0"]
qwen = ["tiktoken", "transformers_stream_generator"]
modelscope = ["modelscope"]
quality = ["ruff"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
mypy_path = "stubs"
strict = true
plugins = [
    "pydantic.mypy"
]
exclude = [
    'src/llmtuner'
]

[[tool.mypy.overrides]]
module = "transformers.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
