# model
model_name_or_path: meta-llama/Meta-Llama-3-8B
adapter_name_or_path: saves/llama3-8b/lora/rm

# method
stage: sotopia_rm
do_train: false
do_eval: true
do_predict: true
finetuning_type: lora
lora_target: q_proj,v_proj

# dataset
dataset: sotopia_pi_utterance_reward
template: llama3
cutoff_len: 1024
max_samples: 1000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/llama3-8b/lora/rm
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 5
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 20