# model
model_name_or_path: ../Mistral-7B-Instruct-v0.3

# method
stage: sotopia_sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

# dataset
dataset: sotopia_pi_gpt4_sft
template: mistral
cutoff_len: 4096
max_samples: 10000000
val_size: 0.01
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/mistral-7b-instruct/lora/gpt4_sft_ds
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 0.0005
num_train_epochs: 30.0
lr_scheduler_type: cosine
warmup_steps: 0
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 200
